@startuml
'https://plantuml.com/class-diagram



class App {
+ main()
+ start()
}

class ToDoList {
- toDoTitle : String
- items[] : ArrayList<Item>
setTitle()
addItem()
removeItem()
}

class Item {
- itemStatus : boolean
- itemDescription : String
- itemDueDate : String

editDescription()
editStatus()
editDueDate()
}

class ListManager {
- openButton : Button
- addButton : Button
- removeButton : Button
- clearButton : Button
- toDoListItems : ListView<Item>
- completeItems :ListView<Item>
- showCompleteItems : RadioButton
- itemDescription : TextField
- itemDue : DatePicker
- isComplete : RadioButton

openButtonIsClicked(ActionEvent actionEvent)
addButtonIsClicked(ActionEvent actionEvent)
removeButtonIsClicked(ActionEvent actionEvent)
clearButtonIsClicked(ActionEvent actionEvent)
setItemDescription(ActionEvent actionEvent)
setItemDue(ActionEvent actionEvent)
setItemStatus(ActionEvent actionEvent)
}

javafx.Application <|- App
App *-- ToDoList
ToDoList o-- Item
ListManager - Item


@enduml